//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdresDefteri.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAdresDefteri
    {
        public int id { get; set; }
        public string AdSoyad { get; set; }
        public string TC { get; set; }
        public string SabitTel { get; set; }
        public string CepTel { get; set; }
        public string Adres { get; set; }
        public string İlce { get; set; }
        public string İl { get; set; }
    }
}
